### PR TITLE
Create nl_nl.json

### PR DESCRIPTION
**Pull request by Raymonzut**
Dutch translations added

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by Raymonzut** [comment]
It ain't much, but It's honest work

**Comment by MrCrayfish** [comment]
Hey @Raymonzut, I am currently relicensing Golden Hopper to a more suitable license. I would like your permission to relicense your contributions to Golden Hopper under MIT. Thank you.

**Comment by Raymonzut** [comment]
Hello @MrCrayfish, I decline the request of permission to relicense these contributions to fall under the MIT license, to ensure contributions towards this project and derived works are shared.

Currently if someone creates their own version based on this project, and does not distribute it, they can do whatever they want. However, I think it is beneficial for distributed versions to be shared as openly as this project; that derived projects also share their changes to the community, which is why I favor the original license.

I appreciate that you take the time to reach out to contributors, thanks for asking.

**Comment by MrCrayfish** [comment]
@Raymonzut Thanks for the quick reply. I respect your decision and appreciate your contributions, this however means your translations will no longer be available in future releases.

**Comment by Raymonzut** [comment]
@MrCrayfish Likewise, then these translations shall be removed upon relicensing, I understand your decision.

**Pull request merged**
