### PR TITLE
1.16/upgrade

### PR DESCRIPTION
**Pull request by puggan**
Now working with 1.16.1
(This PR is a continuation of PR #7)

Kept a comment with `// TODO MCP-name: ` on all missing names, so its easy to change back when the MCP-mappings get up to date.

(You maybe want to merge this PR to a 1.16.x branch)

### CODE REVIEW

**Comment by MrCrayfish** [comment]
I've gone ahead and created a 1.16.X branch on the repo. Can you update it for that branch instead of 1.15.X?

**Comment by puggan** [comment]
Sure, done.
I belived that you as the owner of the repo also had that "power".

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by dfgdfgdfgyhklj** [comment]
Are you still trying to update the mod to 1.16.1?

**Comment by MrCrayfish** [comment]
Hey @puggan , I am currently relicensing Golden Hopper to a more suitable license. I would like your permission to relicense your contributions to Golden Hopper under MIT. Thank you.

**Comment by puggan** [comment]
Sure, you can do whatever you want with my contributions. And i like MIT. All my plugins are MIT.

**Pull request merged**
